# Generated by Django 5.2.7 on 2026-09-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descricao', models.TextField()),
                ('tecnologias', models.CharField(help_text='Separe por vírgula, ex: Python, Django, React', max_length=200)),
                ('imagem_url', models.URLField(blank=True)),
                ('link_projeto', models.URLField(blank=True)),
                ('link_repositorio', models.URLField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
